version: '3.8'
services:
  database:
    build:
      context: ./infrastructure/database
      dockerfile: Dockerfile
    image: yousunkmybattleship_database:latest
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  service:
    build:
      context: .
      dockerfile: ./infrastructure/service/Dockerfile
    image: yousunkmybattleship_service:latest
    restart: "no"
    ports:
      - "8080:8080"
    depends_on:
      - database

  smoketest:
    build:
      context: .
      dockerfile: ./infrastructure/contract_test/Dockerfile
    image: yousunkmybattleship_smoketest:latest
    restart: "no"
    depends_on:
      - service

volumes:
  db_data:
    driver: local
